name: Playwright Tests

on:
  push:
    branches:
      - master  # Запускать на пуши в master
  pull_request:
    branches:
      - master  # Запускать при открытии PR в master

jobs:
  test:
    runs-on: ubuntu-latest  # Выбираем ОС для тестирования

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Клонируем репозиторий

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Указываем нужную версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Устанавливаем зависимости из requirements.txt

      - name: Install Playwright and dependencies
        run: |
          python -m playwright install  # Устанавливаем Playwright и браузеры

      - name: Run Playwright tests
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Запускаем тесты
